# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cloud_cache}
  s.version = "1.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Travis Reeder"]
  s.date = %q{2010-09-19}
  s.description = %q{Client library for Quetzall's CloudCache service.}
  s.email = %q{travis@appoxy.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "lib/cloud_cache.rb",
     "lib/hmac-sha1.rb",
     "lib/hmac.rb"
  ]
  s.homepage = %q{http://github.com/quetzall/cloud_cache/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Client library for Quetzall's CloudCache service.}
  s.test_files = [
    "test/cache_tests.rb",
     "test/my_class.rb",
     "test/test_runner.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<http_connection>, [">= 0"])
    else
      s.add_dependency(%q<http_connection>, [">= 0"])
    end
  else
    s.add_dependency(%q<http_connection>, [">= 0"])
  end
end

